package com.roy.drisk.mybatis.mappers;


import java.util.List;

public interface BlackInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);
	
	int deleteByRealKey(BlackInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	int insert(BlackInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	int insertSelective(BlackInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	BlackInfo selectByPrimaryKey(String id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	BlackInfo selectMaxByRealKey(BlackInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BlackInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table BLACK_INFO
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BlackInfo record);

	/**
	 * 
	 * 统计真实key对应的记录条数
	 * 
	 * @param record
	 * @return
	 */
	int countByRealKey(BlackInfo record);

	/**
	 * 
	 * update 真实key对应的记录条数
	 * 
	 * @param record
	 * @return
	 */
	int updateByRealKey(BlackInfo record);
	/**
	 * 查找所有生效的黑名单信息
	 * @param record 黑名单信息
	 * @return List<BlackInfo>
	 */
	List<BlackInfo> selectAllBlack(BlackInfo record);
	/**
	 * 查找单个生效的黑名单信息
	 * @param record 黑名单信息
	 * @return List<BlackInfo>
	 */
	List<BlackInfo> selectSingleBlack(BlackInfo record);
	
	int updateExpDtByMercId(BlackInfo record);
	
}