package com.roy.drisk.mybatis.mappers;

import java.util.Date;

public class BlackInfo {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.ID
	 *
	 * @mbg.generated
	 */
	private String id;

	private String blackFlag;//加黑原因、涉案标志、加黑标识

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.BLACK_TYPE
	 *
	 * @mbg.generated
	 */
	private String blackType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.KEY_ID
	 *
	 * @mbg.generated
	 */
	private String keyId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.TX_TYP
	 *
	 * @mbg.generated
	 */
	private String txTyp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.BUS_TYP
	 *
	 * @mbg.generated
	 */
	private String busTyp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.EXP_DT
	 *
	 * @mbg.generated
	 */
	private String expDt;
	//已存在黑名单记录中的过期时间
	private String oldExpDt;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.REASON
	 *
	 * @mbg.generated
	 */
	private String reason;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.CREATE_BY
	 *
	 * @mbg.generated
	 */
	private String createBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.CREATE_DATE
	 *
	 * @mbg.generated
	 */
	private Date createDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.UPDATE_BY
	 *
	 * @mbg.generated
	 */
	private String updateBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.UPDATE_DATE
	 *
	 * @mbg.generated
	 */
	private Date updateDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column BLACK_INFO.REMARKS
	 *
	 * @mbg.generated
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.ID
	 *
	 * @return the value of BLACK_INFO.ID
	 *
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.ID
	 *
	 * @param id
	 *            the value for BLACK_INFO.ID
	 *
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.BLACK_TYPE
	 *
	 * @return the value of BLACK_INFO.BLACK_TYPE
	 *
	 * @mbg.generated
	 */
	public String getBlackType() {
		return blackType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.BLACK_TYPE
	 *
	 * @param blackType
	 *            the value for BLACK_INFO.BLACK_TYPE
	 *
	 * @mbg.generated
	 */
	public void setBlackType(String blackType) {
		this.blackType = blackType == null ? null : blackType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.KEY_ID
	 *
	 * @return the value of BLACK_INFO.KEY_ID
	 *
	 * @mbg.generated
	 */
	public String getKeyId() {
		return keyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.KEY_ID
	 *
	 * @param keyId
	 *            the value for BLACK_INFO.KEY_ID
	 *
	 * @mbg.generated
	 */
	public void setKeyId(String keyId) {
		this.keyId = keyId == null ? null : keyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.TX_TYP
	 *
	 * @return the value of BLACK_INFO.TX_TYP
	 *
	 * @mbg.generated
	 */
	public String getTxTyp() {
		return txTyp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.TX_TYP
	 *
	 * @param txTyp
	 *            the value for BLACK_INFO.TX_TYP
	 *
	 * @mbg.generated
	 */
	public void setTxTyp(String txTyp) {
		this.txTyp = txTyp == null ? null : txTyp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.BUS_TYP
	 *
	 * @return the value of BLACK_INFO.BUS_TYP
	 *
	 * @mbg.generated
	 */
	public String getBusTyp() {
		return busTyp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.BUS_TYP
	 *
	 * @param busTyp
	 *            the value for BLACK_INFO.BUS_TYP
	 *
	 * @mbg.generated
	 */
	public void setBusTyp(String busTyp) {
		this.busTyp = busTyp == null ? null : busTyp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.EXP_DT
	 *
	 * @return the value of BLACK_INFO.EXP_DT
	 *
	 * @mbg.generated
	 */
	public String getExpDt() {
		return expDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.EXP_DT
	 *
	 * @param expDt
	 *            the value for BLACK_INFO.EXP_DT
	 *
	 * @mbg.generated
	 */
	public void setExpDt(String expDt) {
		this.expDt = expDt == null ? null : expDt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.REASON
	 *
	 * @return the value of BLACK_INFO.REASON
	 *
	 * @mbg.generated
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.REASON
	 *
	 * @param reason
	 *            the value for BLACK_INFO.REASON
	 *
	 * @mbg.generated
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.CREATE_BY
	 *
	 * @return the value of BLACK_INFO.CREATE_BY
	 *
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.CREATE_BY
	 *
	 * @param createBy
	 *            the value for BLACK_INFO.CREATE_BY
	 *
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.CREATE_DATE
	 *
	 * @return the value of BLACK_INFO.CREATE_DATE
	 *
	 * @mbg.generated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.CREATE_DATE
	 *
	 * @param createDate
	 *            the value for BLACK_INFO.CREATE_DATE
	 *
	 * @mbg.generated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.UPDATE_BY
	 *
	 * @return the value of BLACK_INFO.UPDATE_BY
	 *
	 * @mbg.generated
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.UPDATE_BY
	 *
	 * @param updateBy
	 *            the value for BLACK_INFO.UPDATE_BY
	 *
	 * @mbg.generated
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.UPDATE_DATE
	 *
	 * @return the value of BLACK_INFO.UPDATE_DATE
	 *
	 * @mbg.generated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.UPDATE_DATE
	 *
	 * @param updateDate
	 *            the value for BLACK_INFO.UPDATE_DATE
	 *
	 * @mbg.generated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column BLACK_INFO.REMARKS
	 *
	 * @return the value of BLACK_INFO.REMARKS
	 *
	 * @mbg.generated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column BLACK_INFO.REMARKS
	 *
	 * @param remarks
	 *            the value for BLACK_INFO.REMARKS
	 *
	 * @mbg.generated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	public String getBlackFlag() {
		return blackFlag;
	}

	public void setBlackFlag(String blackFlag) {
		this.blackFlag = blackFlag;
	}

	@Override
	public String toString() {
		return "BlackInfo [id=" + id + ", blackFlag=" + blackFlag + ", blackType=" + blackType + ", keyId=" + keyId + ", txTyp=" + txTyp + ", busTyp=" + busTyp + ", expDt=" + expDt + ", reason=" + reason + ", createBy=" + createBy + ", createDate=" + createDate + ", updateBy=" + updateBy + ", updateDate=" + updateDate + ", remarks=" + remarks + "]";
	}

	public String getOldExpDt() {
		return oldExpDt;
	}

	public void setOldExpDt(String oldExpDt) {
		this.oldExpDt = oldExpDt;
	}

}